development:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_HOST") %>:<%= ENV.fetch("REDIS_PORT") %>/1
  channel_prefix: myapp_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://<%= ENV.fetch("REDIS_HOST") %>:<%= ENV.fetch("REDIS_PORT") %>/1
  channel_prefix: myapp_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
